apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
  - image: ishwarik7/docker-web-app:latest
    name: nodewebapp
    imagePullPolicy: Never
    ports:
    - containerPort: 3001
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  

