version: '3'
services:
  app:
    image: ishwarik7/docker_image_7c
    restart: always
    ports:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3